// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MessageTextSound","status":true,"description":"v1.00 - 为事件的“显示文字”动作添加音效。","parameters":{"Text Sound Interval":"7","Text Sound Name":"Cursor1","Text Sound Volume":"100","Text Sound Pitch":"100","Text Sound Pan":"0"}},
{"name":"YEP_MessageCore","status":true,"description":"v1.17 信息核心","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward Key":"pagedown","Enable Fast Forward":"true","Word Wrapping":"false","Description Wrap":"false","Word Wrap Space":"false","Tight Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","Font Outline":"4","Maintain Font":"false","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]","Name Box Auto Close":"false"}},
{"name":"闫_AI","status":true,"description":"处理AI特效","parameters":{}},
{"name":"闫_StoryControl","status":true,"description":"管理和处理游戏剧情用","parameters":{}},
{"name":"闫_User","status":true,"description":"玩家自定义代码","parameters":{}},
{"name":"闫_DAO","status":true,"description":"","parameters":{}},
{"name":"闫_服务器","status":true,"description":"","parameters":{}},
{"name":"闫_事件点击","status":true,"description":"本插件用于给一个事件添加可以鼠标左键点击的效果","parameters":{}},
{"name":"闫_触发条件修改","status":true,"description":"","parameters":{}},
{"name":"闫_状态界面拓展","status":true,"description":"","parameters":{}},
{"name":"闫_DataController","status":true,"description":"处理游戏的剧情数据","parameters":{}},
{"name":"WindowIdentifier","status":false,"description":"Shows the name of the windows while holding CTRL.","parameters":{"Font Size":"28","Font Color":"0"}},
{"name":"闫_TitleSceneChange","status":true,"description":"","parameters":{}},
{"name":"闫_CharacterController","status":true,"description":"管理角色的各种数据","parameters":{}},
{"name":"闫_AchievementSystem","status":true,"description":"成就系统","parameters":{}},
{"name":"闫_弹幕系统","status":true,"description":"弹幕系统","parameters":{}},
{"name":"闫_Util","status":true,"description":"","parameters":{}},
{"name":"闫_SaveController","status":true,"description":"本类负责游戏的存档，和DataController配合使用","parameters":{}}
];
